"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { PageWrapper } from "@/components/page-wrapper"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { DollarSign, Download, FileImage, RefreshCw, ArrowRightLeft } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import jsPDF from "jspdf"
import "jspdf-autotable"
import html2canvas from "html2canvas"

interface ExchangeRates {
  [key: string]: number
}

interface ConversionHistory {
  id: string
  fromCurrency: string
  toCurrency: string
  amount: number
  result: number
  rate: number
  timestamp: string
}

const currencies = {
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  USD: { name: "US Dollar", symbol: "$" },
  EUR: { name: "Euro", symbol: "€" },
  GBP: { name: "British Pound", symbol: "£" },
  ARS: { name: "Argentine Peso", symbol: "$" },
}

// Default exchange rates (PKR as base)
const defaultRates: ExchangeRates = {
  PKR: 1,
  USD: 0.0036, // 1 PKR = 0.0036 USD
  EUR: 0.0033, // 1 PKR = 0.0033 EUR
  GBP: 0.0028, // 1 PKR = 0.0028 GBP
  ARS: 0.36, // 1 PKR = 0.36 ARS
}

export default function CurrencyConverterPage() {
  const { toast } = useToast()
  const [rates, setRates] = useState<ExchangeRates>(defaultRates)
  const [amount, setAmount] = useState<number>(1)
  const [fromCurrency, setFromCurrency] = useState<string>("PKR")
  const [toCurrency, setToCurrency] = useState<string>("USD")
  const [result, setResult] = useState<number>(0)
  const [history, setHistory] = useState<ConversionHistory[]>([])
  const [customRates, setCustomRates] = useState<ExchangeRates>({})

  // Load data from localStorage
  useEffect(() => {
    const savedRates = localStorage.getItem("currencyRates")
    const savedHistory = localStorage.getItem("conversionHistory")

    if (savedRates) {
      setRates(JSON.parse(savedRates))
    }
    if (savedHistory) {
      setHistory(JSON.parse(savedHistory))
    }
  }, [])

  // Save to localStorage
  useEffect(() => {
    localStorage.setItem("currencyRates", JSON.stringify(rates))
  }, [rates])

  useEffect(() => {
    localStorage.setItem("conversionHistory", JSON.stringify(history))
  }, [history])

  // Calculate conversion
  useEffect(() => {
    if (amount && fromCurrency && toCurrency) {
      const fromRate = rates[fromCurrency]
      const toRate = rates[toCurrency]
      const convertedAmount = (amount / fromRate) * toRate
      setResult(convertedAmount)
    }
  }, [amount, fromCurrency, toCurrency, rates])

  const performConversion = () => {
    if (!amount || amount <= 0) {
      toast({
        title: "Invalid Amount",
        description: "Please enter a valid amount to convert.",
        variant: "destructive",
      })
      return
    }

    const conversion: ConversionHistory = {
      id: Date.now().toString(),
      fromCurrency,
      toCurrency,
      amount,
      result,
      rate: rates[toCurrency] / rates[fromCurrency],
      timestamp: new Date().toISOString(),
    }

    setHistory([conversion, ...history.slice(0, 49)]) // Keep last 50 conversions

    toast({
      title: "Conversion Complete",
      description: `${amount} ${fromCurrency} = ${result.toFixed(2)} ${toCurrency}`,
    })
  }

  const swapCurrencies = () => {
    setFromCurrency(toCurrency)
    setToCurrency(fromCurrency)
  }

  const updateRate = (currency: string, newRate: number) => {
    setRates({ ...rates, [currency]: newRate })
    setCustomRates({ ...customRates, [currency]: newRate })
    toast({
      title: "Rate Updated",
      description: `Exchange rate for ${currency} has been updated.`,
    })
  }

  const resetRates = () => {
    setRates(defaultRates)
    setCustomRates({})
    toast({
      title: "Rates Reset",
      description: "Exchange rates have been reset to default values.",
    })
  }

  const clearHistory = () => {
    setHistory([])
    toast({
      title: "History Cleared",
      description: "Conversion history has been cleared.",
    })
  }

  const exportToPDF = async () => {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()

    // Header
    pdf.setFontSize(20)
    pdf.text("Currency Conversion Report", pageWidth / 2, 20, { align: "center" })
    pdf.setFontSize(12)
    pdf.text(`Generated by Swot.works Tools — ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, {
      align: "center",
    })

    let yPosition = 50

    // Current rates
    pdf.setFontSize(14)
    pdf.text("Current Exchange Rates (Base: PKR)", 20, yPosition)
    yPosition += 15

    Object.entries(rates).forEach(([currency, rate]) => {
      if (currency !== "PKR") {
        pdf.setFontSize(12)
        pdf.text(`1 PKR = ${rate.toFixed(6)} ${currency}`, 20, yPosition)
        yPosition += 8
      }
    })

    yPosition += 10

    // Conversion history
    if (history.length > 0) {
      pdf.setFontSize(14)
      pdf.text("Recent Conversions", 20, yPosition)
      yPosition += 10

      const historyData = history
        .slice(0, 20)
        .map((conv) => [
          new Date(conv.timestamp).toLocaleDateString(),
          `${conv.amount} ${conv.fromCurrency}`,
          `${conv.result.toFixed(2)} ${conv.toCurrency}`,
          conv.rate.toFixed(6),
        ])
      ;(pdf as any).autoTable({
        head: [["Date", "From", "To", "Rate"]],
        body: historyData,
        startY: yPosition,
        styles: { fontSize: 10 },
        headStyles: { fillColor: [22, 163, 74] },
      })
    }

    // Footer
    pdf.setFontSize(8)
    pdf.text("Generated by Swot.works Tools — 2025", pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, {
      align: "center",
    })

    pdf.save(`currency-conversion-${new Date().toISOString().split("T")[0]}.pdf`)
    toast({
      title: "PDF Exported",
      description: "Currency conversion report has been exported successfully.",
    })
  }

  const exportToJPEG = async () => {
    const element = document.getElementById("conversion-table")
    if (element) {
      const canvas = await html2canvas(element, { scale: 2 })
      const link = document.createElement("a")
      link.download = `currency-rates-${new Date().toISOString().split("T")[0]}.jpg`
      link.href = canvas.toDataURL("image/jpeg", 0.9)
      link.click()

      toast({
        title: "JPEG Exported",
        description: "Currency conversion table has been exported as JPEG.",
      })
    }
  }

  return (
    <PageWrapper
      title="Currency Converter"
      description="Offline currency conversion with manual rate management and conversion history"
    >
      <div className="space-y-8">
        {/* Currency Converter */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <DollarSign className="w-5 h-5" />
                Currency Converter
              </CardTitle>
              <CardDescription>Convert between major currencies with offline functionality</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-end">
                <div className="space-y-2">
                  <Label htmlFor="amount">Amount</Label>
                  <Input
                    id="amount"
                    type="number"
                    min="0"
                    step="0.01"
                    value={amount}
                    onChange={(e) => setAmount(Number.parseFloat(e.target.value) || 0)}
                    className="text-lg"
                  />
                </div>
                <div className="space-y-2">
                  <Label>From</Label>
                  <Select value={fromCurrency} onValueChange={setFromCurrency}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.entries(currencies).map(([code, { name, symbol }]) => (
                        <SelectItem key={code} value={code}>
                          {code} - {name} ({symbol})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex justify-center">
                  <Button variant="outline" size="sm" onClick={swapCurrencies}>
                    <ArrowRightLeft className="w-4 h-4" />
                  </Button>
                </div>
                <div className="space-y-2">
                  <Label>To</Label>
                  <Select value={toCurrency} onValueChange={setToCurrency}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.entries(currencies).map(([code, { name, symbol }]) => (
                        <SelectItem key={code} value={code}>
                          {code} - {name} ({symbol})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <Button onClick={performConversion} className="bg-green-600 hover:bg-green-700">
                  Convert
                </Button>
              </div>

              {/* Result */}
              <div className="bg-muted p-6 rounded-lg text-center">
                <p className="text-sm text-muted-foreground mb-2">Conversion Result</p>
                <p className="text-3xl font-bold">
                  {amount} {fromCurrency} = {result.toFixed(2)} {toCurrency}
                </p>
                <p className="text-sm text-muted-foreground mt-2">
                  Rate: 1 {fromCurrency} = {(rates[toCurrency] / rates[fromCurrency]).toFixed(6)} {toCurrency}
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Exchange Rates Management */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1, duration: 0.5 }}
        >
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Exchange Rates Management</CardTitle>
                  <CardDescription>Update exchange rates manually (Base: PKR)</CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" onClick={resetRates}>
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Reset to Default
                  </Button>
                  <Button variant="outline" onClick={exportToPDF}>
                    <Download className="w-4 h-4 mr-2" />
                    Export PDF
                  </Button>
                  <Button variant="outline" onClick={exportToJPEG}>
                    <FileImage className="w-4 h-4 mr-2" />
                    Export JPEG
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div id="conversion-table" className="bg-background p-4 rounded-lg">
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {Object.entries(currencies).map(([code, { name, symbol }]) => {
                    if (code === "PKR") return null
                    return (
                      <div key={code} className="space-y-2">
                        <Label>
                          1 PKR = ? {code} ({symbol})
                        </Label>
                        <div className="flex gap-2">
                          <Input
                            type="number"
                            step="0.000001"
                            value={rates[code]}
                            onChange={(e) => updateRate(code, Number.parseFloat(e.target.value) || 0)}
                            className="flex-1"
                          />
                          <div className="text-sm text-muted-foreground flex items-center">
                            {customRates[code] ? "Custom" : "Default"}
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Conversion History */}
        {history.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5 }}
          >
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Conversion History</CardTitle>
                  <Button variant="outline" onClick={clearHistory}>
                    Clear History
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b">
                        <th className="text-left p-2">Date & Time</th>
                        <th className="text-right p-2">From</th>
                        <th className="text-right p-2">To</th>
                        <th className="text-right p-2">Rate</th>
                      </tr>
                    </thead>
                    <tbody>
                      {history.slice(0, 10).map((conversion) => (
                        <tr key={conversion.id} className="border-b hover:bg-muted/50">
                          <td className="p-2">{new Date(conversion.timestamp).toLocaleString()}</td>
                          <td className="text-right p-2">
                            {conversion.amount} {conversion.fromCurrency}
                          </td>
                          <td className="text-right p-2">
                            {conversion.result.toFixed(2)} {conversion.toCurrency}
                          </td>
                          <td className="text-right p-2">{conversion.rate.toFixed(6)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {history.length === 0 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="text-center py-12"
          >
            <DollarSign className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Conversions Yet</h3>
            <p className="text-muted-foreground">
              Perform your first currency conversion to start building your conversion history.
            </p>
          </motion.div>
        )}
      </div>
    </PageWrapper>
  )
}
