import jsPDF from "jspdf"
import html2canvas from "html2canvas"
import "jspdf-autotable"

interface ExportOptions {
  filename: string
  title: string
  data?: any[]
  chartElement?: HTMLElement
  tableElement?: HTMLElement
  customContent?: HTMLElement
}

export const exportToPDF = async (options: ExportOptions) => {
  const { filename, title, data, chartElement, tableElement, customContent } = options

  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.width
  let yPosition = 20

  // Header with logo and title
  pdf.setFontSize(20)
  pdf.setTextColor(22, 163, 74) // Green color
  pdf.text("Swot.works Tools", 20, yPosition)

  pdf.setFontSize(16)
  pdf.setTextColor(0, 0, 0)
  pdf.text(title, 20, yPosition + 15)

  pdf.setFontSize(10)
  pdf.setTextColor(100, 100, 100)
  pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, yPosition + 25)

  yPosition += 40

  // Add chart if provided
  if (chartElement) {
    try {
      const canvas = await html2canvas(chartElement, {
        backgroundColor: "#ffffff",
        scale: 2,
      })
      const imgData = canvas.toDataURL("image/png")
      const imgWidth = pageWidth - 40
      const imgHeight = (canvas.height * imgWidth) / canvas.width

      pdf.addImage(imgData, "PNG", 20, yPosition, imgWidth, imgHeight)
      yPosition += imgHeight + 20
    } catch (error) {
      console.error("Error capturing chart:", error)
    }
  }

  // Add table if provided
  if (tableElement && data) {
    const tableHeaders = Array.from(tableElement.querySelectorAll("th")).map((th) => th.textContent || "")
    const tableRows = data.map((row) => Object.values(row))
    ;(pdf as any).autoTable({
      head: [tableHeaders],
      body: tableRows,
      startY: yPosition,
      theme: "grid",
      headStyles: { fillColor: [22, 163, 74] },
      styles: { fontSize: 8 },
    })

    yPosition = (pdf as any).lastAutoTable.finalY + 20
  }

  // Add custom content if provided
  if (customContent) {
    try {
      const canvas = await html2canvas(customContent, {
        backgroundColor: "#ffffff",
        scale: 2,
      })
      const imgData = canvas.toDataURL("image/png")
      const imgWidth = pageWidth - 40
      const imgHeight = (canvas.height * imgWidth) / canvas.width

      if (yPosition + imgHeight > pdf.internal.pageSize.height - 30) {
        pdf.addPage()
        yPosition = 20
      }

      pdf.addImage(imgData, "PNG", 20, yPosition, imgWidth, imgHeight)
    } catch (error) {
      console.error("Error capturing custom content:", error)
    }
  }

  // Footer
  const pageCount = pdf.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(8)
    pdf.setTextColor(100, 100, 100)
    pdf.text("Generated by Swot.works Tools — 2025", pageWidth / 2, pdf.internal.pageSize.height - 10, {
      align: "center",
    })
  }

  pdf.save(`${filename}.pdf`)
}

export const exportToJPEG = async (element: HTMLElement, filename: string) => {
  try {
    const canvas = await html2canvas(element, {
      backgroundColor: "#ffffff",
      scale: 2,
      width: Math.max(1920, element.offsetWidth),
      height: element.offsetHeight,
    })

    const link = document.createElement("a")
    link.download = `${filename}.jpg`
    link.href = canvas.toDataURL("image/jpeg", 0.9)
    link.click()
  } catch (error) {
    console.error("Error exporting to JPEG:", error)
  }
}

export const exportToCSV = (data: any[], filename: string) => {
  if (!data.length) return

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(","),
    ...data.map((row) => headers.map((header) => `"${row[header] || ""}"`).join(",")),
  ].join("\n")

  const blob = new Blob([csvContent], { type: "text/csv" })
  const link = document.createElement("a")
  link.href = URL.createObjectURL(blob)
  link.download = `${filename}.csv`
  link.click()
}
