"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { PageWrapper } from "@/components/page-wrapper"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { CheckSquare, Plus, Trash2, Download, FileImage, GripVertical } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import jsPDF from "jspdf"
import html2canvas from "html2canvas"

interface Task {
  id: string
  title: string
  description: string
  priority: "low" | "medium" | "high"
  status: "todo" | "in-progress" | "done"
  createdAt: string
  completedAt?: string
}

const priorityColors = {
  low: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
  medium: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
  high: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
}

const statusColumns = {
  todo: { title: "To Do", color: "bg-gray-50 dark:bg-gray-900" },
  "in-progress": { title: "In Progress", color: "bg-blue-50 dark:bg-blue-950" },
  done: { title: "Done", color: "bg-green-50 dark:bg-green-950" },
}

export default function TodoBoardPage() {
  const { toast } = useToast()
  const [tasks, setTasks] = useState<Task[]>([])
  const [newTask, setNewTask] = useState({
    title: "",
    description: "",
    priority: "medium" as Task["priority"],
  })
  const [draggedTask, setDraggedTask] = useState<string | null>(null)

  // Load data from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("todoTasks")
    if (saved) {
      setTasks(JSON.parse(saved))
    }
  }, [])

  // Save to localStorage
  useEffect(() => {
    localStorage.setItem("todoTasks", JSON.stringify(tasks))
  }, [tasks])

  const addTask = () => {
    if (!newTask.title.trim()) {
      toast({
        title: "Invalid Task",
        description: "Please enter a task title.",
        variant: "destructive",
      })
      return
    }

    const task: Task = {
      id: Date.now().toString(),
      title: newTask.title,
      description: newTask.description,
      priority: newTask.priority,
      status: "todo",
      createdAt: new Date().toISOString(),
    }

    setTasks([task, ...tasks])
    setNewTask({ title: "", description: "", priority: "medium" })

    toast({
      title: "Task Added",
      description: "New task has been added to your board.",
    })
  }

  const updateTaskStatus = (taskId: string, newStatus: Task["status"]) => {
    setTasks(
      tasks.map((task) => {
        if (task.id === taskId) {
          const updatedTask = { ...task, status: newStatus }
          if (newStatus === "done" && task.status !== "done") {
            updatedTask.completedAt = new Date().toISOString()
          } else if (newStatus !== "done") {
            delete updatedTask.completedAt
          }
          return updatedTask
        }
        return task
      }),
    )
  }

  const deleteTask = (taskId: string) => {
    setTasks(tasks.filter((task) => task.id !== taskId))
    toast({
      title: "Task Deleted",
      description: "Task has been removed from your board.",
    })
  }

  const clearAllTasks = () => {
    setTasks([])
    toast({
      title: "All Tasks Cleared",
      description: "All tasks have been removed from your board.",
    })
  }

  const getTasksByStatus = (status: Task["status"]) => {
    return tasks.filter((task) => task.status === status)
  }

  const handleDragStart = (e: React.DragEvent, taskId: string) => {
    setDraggedTask(taskId)
    e.dataTransfer.effectAllowed = "move"
  }

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = "move"
  }

  const handleDrop = (e: React.DragEvent, newStatus: Task["status"]) => {
    e.preventDefault()
    if (draggedTask) {
      updateTaskStatus(draggedTask, newStatus)
      setDraggedTask(null)
    }
  }

  const exportToPDF = async () => {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()

    // Header
    pdf.setFontSize(20)
    pdf.text("Task Board Report", pageWidth / 2, 20, { align: "center" })
    pdf.setFontSize(12)
    pdf.text(`Generated by Swot.works Tools — ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, {
      align: "center",
    })

    let yPosition = 50

    // Summary
    const todoCount = getTasksByStatus("todo").length
    const inProgressCount = getTasksByStatus("in-progress").length
    const doneCount = getTasksByStatus("done").length

    pdf.setFontSize(14)
    pdf.text("Summary", 20, yPosition)
    yPosition += 15

    pdf.setFontSize(12)
    pdf.text(`To Do: ${todoCount}`, 20, yPosition)
    pdf.text(`In Progress: ${inProgressCount}`, 70, yPosition)
    pdf.text(`Done: ${doneCount}`, 130, yPosition)
    yPosition += 20

    // Tasks by status
    Object.entries(statusColumns).forEach(([status, { title }]) => {
      const statusTasks = getTasksByStatus(status as Task["status"])
      if (statusTasks.length === 0) return

      if (yPosition > 250) {
        pdf.addPage()
        yPosition = 20
      }

      pdf.setFontSize(16)
      pdf.text(title, 20, yPosition)
      yPosition += 15

      statusTasks.forEach((task) => {
        if (yPosition > 270) {
          pdf.addPage()
          yPosition = 20
        }

        pdf.setFontSize(12)
        pdf.text(`• ${task.title}`, 25, yPosition)
        yPosition += 8

        if (task.description) {
          pdf.setFontSize(10)
          const descLines = pdf.splitTextToSize(task.description, pageWidth - 50)
          pdf.text(descLines, 30, yPosition)
          yPosition += descLines.length * 5
        }

        pdf.setFontSize(9)
        pdf.text(`Priority: ${task.priority.toUpperCase()}`, 30, yPosition)
        yPosition += 6
        pdf.text(`Created: ${new Date(task.createdAt).toLocaleDateString()}`, 30, yPosition)
        if (task.completedAt) {
          yPosition += 6
          pdf.text(`Completed: ${new Date(task.completedAt).toLocaleDateString()}`, 30, yPosition)
        }
        yPosition += 15
      })

      yPosition += 10
    })

    // Footer
    pdf.setFontSize(8)
    pdf.text("Generated by Swot.works Tools — 2025", pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, {
      align: "center",
    })

    pdf.save(`task-board-${new Date().toISOString().split("T")[0]}.pdf`)
    toast({
      title: "PDF Exported",
      description: "Task board has been exported successfully.",
    })
  }

  const exportToJPEG = async () => {
    const element = document.getElementById("kanban-board")
    if (element) {
      const canvas = await html2canvas(element, { scale: 2 })
      const link = document.createElement("a")
      link.download = `task-board-${new Date().toISOString().split("T")[0]}.jpg`
      link.href = canvas.toDataURL("image/jpeg", 0.9)
      link.click()

      toast({
        title: "JPEG Exported",
        description: "Task board has been exported as JPEG.",
      })
    }
  }

  return (
    <PageWrapper
      title="To-Do & Reminder Board"
      description="Organize tasks with drag-and-drop Kanban board and priority management"
    >
      <div className="space-y-8">
        {/* Add Task Form */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Plus className="w-5 h-5" />
                Add New Task
              </CardTitle>
              <CardDescription>Create a new task and assign priority level</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="md:col-span-2 space-y-2">
                  <Label htmlFor="taskTitle">Task Title *</Label>
                  <Input
                    id="taskTitle"
                    placeholder="Enter task title"
                    value={newTask.title}
                    onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="priority">Priority</Label>
                  <Select
                    value={newTask.priority}
                    onValueChange={(value: Task["priority"]) => setNewTask({ ...newTask, priority: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="low">Low</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="high">High</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="taskDescription">Description</Label>
                <Textarea
                  id="taskDescription"
                  placeholder="Enter task description (optional)"
                  value={newTask.description}
                  onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                />
              </div>
              <div className="flex gap-2">
                <Button onClick={addTask} className="bg-green-600 hover:bg-green-700">
                  <Plus className="w-4 h-4 mr-2" />
                  Add Task
                </Button>
                <Button variant="outline" onClick={clearAllTasks}>
                  <Trash2 className="w-4 h-4 mr-2" />
                  Clear All
                </Button>
                <Button variant="outline" onClick={exportToPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  Export PDF
                </Button>
                <Button variant="outline" onClick={exportToJPEG}>
                  <FileImage className="w-4 h-4 mr-2" />
                  Export JPEG
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Kanban Board */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.5 }}
          id="kanban-board"
          className="bg-background p-4 rounded-lg"
        >
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {Object.entries(statusColumns).map(([status, { title, color }]) => {
              const statusTasks = getTasksByStatus(status as Task["status"])
              return (
                <div
                  key={status}
                  className={`${color} rounded-lg p-4 min-h-[400px]`}
                  onDragOver={handleDragOver}
                  onDrop={(e) => handleDrop(e, status as Task["status"])}
                >
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-semibold text-lg">{title}</h3>
                    <Badge variant="secondary">{statusTasks.length}</Badge>
                  </div>

                  <div className="space-y-3">
                    {statusTasks.map((task, index) => (
                      <motion.div
                        key={task.id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1, duration: 0.3 }}
                        draggable
                        onDragStart={(e) => handleDragStart(e, task.id)}
                        className="bg-background border rounded-lg p-3 cursor-move hover:shadow-md transition-shadow"
                      >
                        <div className="flex items-start justify-between mb-2">
                          <h4 className="font-medium text-sm leading-tight">{task.title}</h4>
                          <div className="flex items-center gap-1">
                            <GripVertical className="w-4 h-4 text-muted-foreground" />
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => deleteTask(task.id)}
                              className="h-6 w-6 p-0 hover:bg-destructive hover:text-destructive-foreground"
                            >
                              <Trash2 className="w-3 h-3" />
                            </Button>
                          </div>
                        </div>

                        {task.description && (
                          <p className="text-xs text-muted-foreground mb-2 line-clamp-2">{task.description}</p>
                        )}

                        <div className="flex items-center justify-between">
                          <Badge className={`text-xs ${priorityColors[task.priority]}`}>
                            {task.priority.toUpperCase()}
                          </Badge>
                          <span className="text-xs text-muted-foreground">
                            {new Date(task.createdAt).toLocaleDateString()}
                          </span>
                        </div>

                        {task.completedAt && (
                          <div className="mt-2 text-xs text-green-600 dark:text-green-400">
                            ✓ Completed {new Date(task.completedAt).toLocaleDateString()}
                          </div>
                        )}
                      </motion.div>
                    ))}

                    {statusTasks.length === 0 && (
                      <div className="text-center py-8 text-muted-foreground">
                        <CheckSquare className="w-8 h-8 mx-auto mb-2 opacity-50" />
                        <p className="text-sm">No tasks in {title.toLowerCase()}</p>
                      </div>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        </motion.div>

        {tasks.length === 0 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="text-center py-12"
          >
            <CheckSquare className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Tasks Yet</h3>
            <p className="text-muted-foreground">
              Create your first task to start organizing your work with the Kanban board.
            </p>
          </motion.div>
        )}
      </div>
    </PageWrapper>
  )
}
