"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { PageWrapper } from "@/components/page-wrapper"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { CreditCard, Download, Trash2, Calculator, TrendingDown } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import jsPDF from "jspdf"
import "jspdf-autotable"

interface LoanData {
  id: string
  name: string
  loanAmount: number
  interestRate: number
  termMonths: number
  monthlyPayment: number
  totalInterest: number
  totalCost: number
  createdAt: string
}

interface AmortizationEntry {
  month: number
  payment: number
  principal: number
  interest: number
  balance: number
}

export default function LoanRepaymentPage() {
  const { toast } = useToast()
  const [loans, setLoans] = useState<LoanData[]>([])
  const [currentLoan, setCurrentLoan] = useState<Partial<LoanData>>({
    name: "",
    loanAmount: 0,
    interestRate: 0,
    termMonths: 12,
  })
  const [selectedLoan, setSelectedLoan] = useState<LoanData | null>(null)
  const [amortizationSchedule, setAmortizationSchedule] = useState<AmortizationEntry[]>([])

  // Load data from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("loanRepaymentData")
    if (saved) {
      setLoans(JSON.parse(saved))
    }
  }, [])

  // Save to localStorage
  useEffect(() => {
    localStorage.setItem("loanRepaymentData", JSON.stringify(loans))
  }, [loans])

  const calculateLoan = () => {
    const { loanAmount, interestRate, termMonths } = currentLoan

    if (!loanAmount || !interestRate || !termMonths) {
      toast({
        title: "Invalid Input",
        description: "Please fill in all required fields.",
        variant: "destructive",
      })
      return
    }

    const monthlyRate = interestRate / 100 / 12
    const monthlyPayment =
      (loanAmount * monthlyRate * Math.pow(1 + monthlyRate, termMonths)) / (Math.pow(1 + monthlyRate, termMonths) - 1)

    const totalCost = monthlyPayment * termMonths
    const totalInterest = totalCost - loanAmount

    const newLoan: LoanData = {
      id: Date.now().toString(),
      name: currentLoan.name || `Loan ${loans.length + 1}`,
      loanAmount: loanAmount,
      interestRate: interestRate,
      termMonths: termMonths,
      monthlyPayment,
      totalInterest,
      totalCost,
      createdAt: new Date().toISOString(),
    }

    setLoans([newLoan, ...loans])
    setCurrentLoan({
      name: "",
      loanAmount: 0,
      interestRate: 0,
      termMonths: 12,
    })

    toast({
      title: "Loan Calculated",
      description: `Monthly payment: PKR ${monthlyPayment.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
    })
  }

  const generateAmortizationSchedule = (loan: LoanData) => {
    const schedule: AmortizationEntry[] = []
    const monthlyRate = loan.interestRate / 100 / 12
    let balance = loan.loanAmount

    for (let month = 1; month <= loan.termMonths; month++) {
      const interestPayment = balance * monthlyRate
      const principalPayment = loan.monthlyPayment - interestPayment
      balance -= principalPayment

      schedule.push({
        month,
        payment: loan.monthlyPayment,
        principal: principalPayment,
        interest: interestPayment,
        balance: Math.max(0, balance),
      })
    }

    setAmortizationSchedule(schedule)
    setSelectedLoan(loan)
  }

  const deleteLoan = (id: string) => {
    setLoans(loans.filter((loan) => loan.id !== id))
    if (selectedLoan?.id === id) {
      setSelectedLoan(null)
      setAmortizationSchedule([])
    }
    toast({
      title: "Loan Deleted",
      description: "Loan calculation has been removed.",
    })
  }

  const clearAllData = () => {
    setLoans([])
    setSelectedLoan(null)
    setAmortizationSchedule([])
    setCurrentLoan({
      name: "",
      loanAmount: 0,
      interestRate: 0,
      termMonths: 12,
    })
    toast({
      title: "All Data Cleared",
      description: "All loan calculations have been removed.",
    })
  }

  const exportToPDF = async (loan?: LoanData) => {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()

    // Header
    pdf.setFontSize(20)
    pdf.text("Loan Repayment Analysis", pageWidth / 2, 20, { align: "center" })
    pdf.setFontSize(12)
    pdf.text(`Generated by Swot.works Tools — ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, {
      align: "center",
    })

    let yPosition = 50

    if (loan) {
      // Single loan with amortization schedule
      pdf.setFontSize(16)
      pdf.text(`Loan: ${loan.name}`, 20, yPosition)
      yPosition += 20

      // Loan summary
      const summaryData = [
        ["Loan Amount", `PKR ${loan.loanAmount.toLocaleString()}`],
        ["Interest Rate", `${loan.interestRate}% per annum`],
        ["Term", `${loan.termMonths} months`],
        ["Monthly Payment", `PKR ${loan.monthlyPayment.toLocaleString(undefined, { maximumFractionDigits: 0 })}`],
        ["Total Interest", `PKR ${loan.totalInterest.toLocaleString(undefined, { maximumFractionDigits: 0 })}`],
        ["Total Cost", `PKR ${loan.totalCost.toLocaleString(undefined, { maximumFractionDigits: 0 })}`],
      ]

      summaryData.forEach(([label, value]) => {
        pdf.text(`${label}: ${value}`, 20, yPosition)
        yPosition += 10
      })

      yPosition += 10

      // Amortization schedule
      if (amortizationSchedule.length > 0) {
        pdf.setFontSize(14)
        pdf.text("Amortization Schedule", 20, yPosition)
        yPosition += 10

        const scheduleData = amortizationSchedule.map((entry) => [
          entry.month.toString(),
          `PKR ${entry.payment.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
          `PKR ${entry.principal.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
          `PKR ${entry.interest.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
          `PKR ${entry.balance.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
        ])
        ;(pdf as any).autoTable({
          head: [["Month", "Payment", "Principal", "Interest", "Balance"]],
          body: scheduleData,
          startY: yPosition,
          styles: { fontSize: 8 },
          headStyles: { fillColor: [22, 163, 74] },
        })
      }
    } else {
      // All loans summary
      loans.forEach((loan, index) => {
        if (yPosition > 250) {
          pdf.addPage()
          yPosition = 20
        }

        pdf.setFontSize(14)
        pdf.text(`${index + 1}. ${loan.name}`, 20, yPosition)
        yPosition += 10

        pdf.setFontSize(10)
        pdf.text(
          `Monthly Payment: PKR ${loan.monthlyPayment.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
          25,
          yPosition,
        )
        yPosition += 8
        pdf.text(
          `Total Interest: PKR ${loan.totalInterest.toLocaleString(undefined, { maximumFractionDigits: 0 })}`,
          25,
          yPosition,
        )
        yPosition += 15
      })
    }

    // Footer
    const pageCount = pdf.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.text("Generated by Swot.works Tools — 2025", pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, {
        align: "center",
      })
    }

    pdf.save(`loan-repayment-${new Date().toISOString().split("T")[0]}.pdf`)
    toast({
      title: "PDF Exported",
      description: "Loan repayment analysis has been exported successfully.",
    })
  }

  return (
    <PageWrapper
      title="Loan Repayment Planner"
      description="Calculate loan payments with detailed amortization schedules and comprehensive analysis"
    >
      <div className="space-y-8">
        {/* Input Form */}
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CreditCard className="w-5 h-5" />
                Loan Calculator
              </CardTitle>
              <CardDescription>Enter loan details to calculate monthly payments and total costs</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="loanName">Loan Name</Label>
                  <Input
                    id="loanName"
                    placeholder="e.g., Business Equipment Loan"
                    value={currentLoan.name}
                    onChange={(e) => setCurrentLoan({ ...currentLoan, name: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="loanAmount">Loan Amount (PKR)</Label>
                  <Input
                    id="loanAmount"
                    type="number"
                    placeholder="e.g., 500000"
                    value={currentLoan.loanAmount || ""}
                    onChange={(e) =>
                      setCurrentLoan({ ...currentLoan, loanAmount: Number.parseFloat(e.target.value) || 0 })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="interestRate">Interest Rate (% per annum)</Label>
                  <Input
                    id="interestRate"
                    type="number"
                    step="0.1"
                    placeholder="e.g., 12.5"
                    value={currentLoan.interestRate || ""}
                    onChange={(e) =>
                      setCurrentLoan({ ...currentLoan, interestRate: Number.parseFloat(e.target.value) || 0 })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="termMonths">Loan Term</Label>
                  <Select
                    value={currentLoan.termMonths?.toString()}
                    onValueChange={(value) => setCurrentLoan({ ...currentLoan, termMonths: Number.parseInt(value) })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select term" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="6">6 months</SelectItem>
                      <SelectItem value="12">1 year</SelectItem>
                      <SelectItem value="24">2 years</SelectItem>
                      <SelectItem value="36">3 years</SelectItem>
                      <SelectItem value="48">4 years</SelectItem>
                      <SelectItem value="60">5 years</SelectItem>
                      <SelectItem value="120">10 years</SelectItem>
                      <SelectItem value="180">15 years</SelectItem>
                      <SelectItem value="240">20 years</SelectItem>
                      <SelectItem value="300">25 years</SelectItem>
                      <SelectItem value="360">30 years</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="flex gap-2">
                <Button onClick={calculateLoan} className="bg-green-600 hover:bg-green-700">
                  <Calculator className="w-4 h-4 mr-2" />
                  Calculate Loan
                </Button>
                <Button variant="outline" onClick={clearAllData}>
                  <Trash2 className="w-4 h-4 mr-2" />
                  Clear All
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Loan Results */}
        {loans.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5 }}
            className="space-y-6"
          >
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-bold">Loan Calculations</h2>
              <Button onClick={() => exportToPDF()} variant="outline">
                <Download className="w-4 h-4 mr-2" />
                Export All PDF
              </Button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {loans.map((loan, index) => (
                <motion.div
                  key={loan.id}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1, duration: 0.3 }}
                >
                  <Card className={selectedLoan?.id === loan.id ? "ring-2 ring-green-500" : ""}>
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <CardTitle className="flex items-center gap-2">
                          <TrendingDown className="w-5 h-5" />
                          {loan.name}
                        </CardTitle>
                        <div className="flex gap-2">
                          <Button size="sm" variant="outline" onClick={() => exportToPDF(loan)}>
                            <Download className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="destructive" onClick={() => deleteLoan(loan.id)}>
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                      <CardDescription>Created on {new Date(loan.createdAt).toLocaleDateString()}</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-green-50 dark:bg-green-950 p-3 rounded-lg">
                          <p className="text-sm text-muted-foreground">Monthly Payment</p>
                          <p className="text-xl font-bold text-green-600">
                            PKR {loan.monthlyPayment.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </p>
                        </div>
                        <div className="bg-red-50 dark:bg-red-950 p-3 rounded-lg">
                          <p className="text-sm text-muted-foreground">Total Interest</p>
                          <p className="text-xl font-bold text-red-600">
                            PKR {loan.totalInterest.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </p>
                        </div>
                      </div>

                      <div className="text-sm space-y-1">
                        <p>Loan Amount: PKR {loan.loanAmount.toLocaleString()}</p>
                        <p>Interest Rate: {loan.interestRate}% per annum</p>
                        <p>Term: {loan.termMonths} months</p>
                        <p>Total Cost: PKR {loan.totalCost.toLocaleString(undefined, { maximumFractionDigits: 0 })}</p>
                      </div>

                      <Button onClick={() => generateAmortizationSchedule(loan)} variant="outline" className="w-full">
                        View Amortization Schedule
                      </Button>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}

        {/* Amortization Schedule */}
        {selectedLoan && amortizationSchedule.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Amortization Schedule - {selectedLoan.name}</CardTitle>
                <CardDescription>Detailed month-by-month payment breakdown</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b">
                        <th className="text-left p-2">Month</th>
                        <th className="text-right p-2">Payment</th>
                        <th className="text-right p-2">Principal</th>
                        <th className="text-right p-2">Interest</th>
                        <th className="text-right p-2">Balance</th>
                      </tr>
                    </thead>
                    <tbody>
                      {amortizationSchedule.map((entry) => (
                        <tr key={entry.month} className="border-b hover:bg-muted/50">
                          <td className="p-2">{entry.month}</td>
                          <td className="text-right p-2">
                            PKR {entry.payment.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </td>
                          <td className="text-right p-2 text-green-600">
                            PKR {entry.principal.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </td>
                          <td className="text-right p-2 text-red-600">
                            PKR {entry.interest.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </td>
                          <td className="text-right p-2">
                            PKR {entry.balance.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {loans.length === 0 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="text-center py-12"
          >
            <CreditCard className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Loan Calculations Yet</h3>
            <p className="text-muted-foreground">
              Create your first loan calculation to plan your repayment strategy and understand total costs.
            </p>
          </motion.div>
        )}
      </div>
    </PageWrapper>
  )
}
