"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { PageWrapper } from "@/components/page-wrapper"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Package, Plus, Trash2, Download, FileImage, AlertTriangle, TrendingUp } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import jsPDF from "jspdf"
import "jspdf-autotable"
import html2canvas from "html2canvas"

interface Product {
  id: string
  name: string
  quantity: number
  costPrice: number
  sellingPrice: number
  lowStockThreshold: number
  category: string
  createdAt: string
  lastUpdated: string
}

export default function InventoryTrackerPage() {
  const { toast } = useToast()
  const [products, setProducts] = useState<Product[]>([])
  const [newProduct, setNewProduct] = useState({
    name: "",
    quantity: 0,
    costPrice: 0,
    sellingPrice: 0,
    lowStockThreshold: 10,
    category: "",
  })
  const [searchTerm, setSearchTerm] = useState("")
  const [filterCategory, setFilterCategory] = useState("")

  // Load data from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("inventoryProducts")
    if (saved) {
      setProducts(JSON.parse(saved))
    }
  }, [])

  // Save to localStorage
  useEffect(() => {
    localStorage.setItem("inventoryProducts", JSON.stringify(products))
  }, [products])

  const addProduct = () => {
    if (!newProduct.name.trim()) {
      toast({
        title: "Invalid Product",
        description: "Please enter a product name.",
        variant: "destructive",
      })
      return
    }

    const product: Product = {
      id: Date.now().toString(),
      name: newProduct.name,
      quantity: newProduct.quantity,
      costPrice: newProduct.costPrice,
      sellingPrice: newProduct.sellingPrice,
      lowStockThreshold: newProduct.lowStockThreshold,
      category: newProduct.category || "General",
      createdAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
    }

    setProducts([product, ...products])
    setNewProduct({
      name: "",
      quantity: 0,
      costPrice: 0,
      sellingPrice: 0,
      lowStockThreshold: 10,
      category: "",
    })

    toast({
      title: "Product Added",
      description: "New product has been added to your inventory.",
    })
  }

  const updateProduct = (id: string, field: keyof Product, value: string | number) => {
    setProducts(
      products.map((product) => {
        if (product.id === id) {
          return {
            ...product,
            [field]: value,
            lastUpdated: new Date().toISOString(),
          }
        }
        return product
      }),
    )
  }

  const deleteProduct = (id: string) => {
    setProducts(products.filter((product) => product.id !== id))
    toast({
      title: "Product Deleted",
      description: "Product has been removed from your inventory.",
    })
  }

  const clearAllProducts = () => {
    setProducts([])
    setNewProduct({
      name: "",
      quantity: 0,
      costPrice: 0,
      sellingPrice: 0,
      lowStockThreshold: 10,
      category: "",
    })
    toast({
      title: "All Products Cleared",
      description: "All products have been removed from your inventory.",
    })
  }

  const getFilteredProducts = () => {
    return products.filter((product) => {
      const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase())
      const matchesCategory = !filterCategory || product.category === filterCategory
      return matchesSearch && matchesCategory
    })
  }

  const getLowStockProducts = () => {
    return products.filter((product) => product.quantity <= product.lowStockThreshold)
  }

  const getCategories = () => {
    return Array.from(new Set(products.map((product) => product.category)))
  }

  const getTotalValue = () => {
    return products.reduce((total, product) => total + product.quantity * product.costPrice, 0)
  }

  const getTotalPotentialProfit = () => {
    return products.reduce((total, product) => total + product.quantity * (product.sellingPrice - product.costPrice), 0)
  }

  const exportToPDF = async () => {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()

    // Header
    pdf.setFontSize(20)
    pdf.text("Inventory Report", pageWidth / 2, 20, { align: "center" })
    pdf.setFontSize(12)
    pdf.text(`Generated by Swot.works Tools — ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, {
      align: "center",
    })

    let yPosition = 50

    // Summary
    pdf.setFontSize(14)
    pdf.text("Summary", 20, yPosition)
    yPosition += 15

    pdf.setFontSize(12)
    pdf.text(`Total Products: ${products.length}`, 20, yPosition)
    yPosition += 8
    pdf.text(`Low Stock Items: ${getLowStockProducts().length}`, 20, yPosition)
    yPosition += 8
    pdf.text(`Total Inventory Value: PKR ${getTotalValue().toLocaleString()}`, 20, yPosition)
    yPosition += 8
    pdf.text(`Potential Profit: PKR ${getTotalPotentialProfit().toLocaleString()}`, 20, yPosition)
    yPosition += 20

    // Products table
    const tableData = products.map((product) => [
      product.name,
      product.category,
      product.quantity.toString(),
      `PKR ${product.costPrice.toLocaleString()}`,
      `PKR ${product.sellingPrice.toLocaleString()}`,
      `PKR ${((product.sellingPrice - product.costPrice) * product.quantity).toLocaleString()}`,
      product.quantity <= product.lowStockThreshold ? "Low Stock" : "OK",
    ])
    ;(pdf as any).autoTable({
      head: [["Product", "Category", "Qty", "Cost", "Selling", "Profit", "Status"]],
      body: tableData,
      startY: yPosition,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [22, 163, 74] },
      columnStyles: {
        6: { textColor: [239, 68, 68] }, // Status column in red for low stock
      },
    })

    // Footer
    pdf.setFontSize(8)
    pdf.text("Generated by Swot.works Tools — 2025", pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, {
      align: "center",
    })

    pdf.save(`inventory-report-${new Date().toISOString().split("T")[0]}.pdf`)
    toast({
      title: "PDF Exported",
      description: "Inventory report has been exported successfully.",
    })
  }

  const exportToJPEG = async () => {
    const element = document.getElementById("inventory-table")
    if (element) {
      const canvas = await html2canvas(element, { scale: 2 })
      const link = document.createElement("a")
      link.download = `inventory-${new Date().toISOString().split("T")[0]}.jpg`
      link.href = canvas.toDataURL("image/jpeg", 0.9)
      link.click()

      toast({
        title: "JPEG Exported",
        description: "Inventory table has been exported as JPEG.",
      })
    }
  }

  const filteredProducts = getFilteredProducts()
  const lowStockProducts = getLowStockProducts()
  const categories = getCategories()

  return (
    <PageWrapper
      title="Simple Inventory Tracker"
      description="Track products with low-stock alerts and profit margin analysis"
    >
      <div className="space-y-8">
        {/* Low Stock Alert */}
        {lowStockProducts.length > 0 && (
          <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <Alert className="border-orange-200 bg-orange-50 dark:border-orange-800 dark:bg-orange-950">
              <AlertTriangle className="h-4 w-4 text-orange-600" />
              <AlertDescription className="text-orange-800 dark:text-orange-200">
                <strong>Low Stock Alert:</strong> {lowStockProducts.length} product(s) are running low on stock.
              </AlertDescription>
            </Alert>
          </motion.div>
        )}

        {/* Summary Cards */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="grid grid-cols-1 md:grid-cols-4 gap-4"
        >
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <Package className="w-5 h-5 text-blue-600" />
                <div>
                  <p className="text-sm text-muted-foreground">Total Products</p>
                  <p className="text-2xl font-bold">{products.length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-orange-600" />
                <div>
                  <p className="text-sm text-muted-foreground">Low Stock</p>
                  <p className="text-2xl font-bold text-orange-600">{lowStockProducts.length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-green-600" />
                <div>
                  <p className="text-sm text-muted-foreground">Inventory Value</p>
                  <p className="text-2xl font-bold">PKR {getTotalValue().toLocaleString()}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-purple-600" />
                <div>
                  <p className="text-sm text-muted-foreground">Potential Profit</p>
                  <p className="text-2xl font-bold text-green-600">PKR {getTotalPotentialProfit().toLocaleString()}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Add Product Form */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1, duration: 0.5 }}
        >
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Plus className="w-5 h-5" />
                Add New Product
              </CardTitle>
              <CardDescription>Add products to your inventory with cost and pricing information</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="productName">Product Name *</Label>
                  <Input
                    id="productName"
                    placeholder="Enter product name"
                    value={newProduct.name}
                    onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="category">Category</Label>
                  <Input
                    id="category"
                    placeholder="e.g., Electronics, Clothing"
                    value={newProduct.category}
                    onChange={(e) => setNewProduct({ ...newProduct, category: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="quantity">Quantity</Label>
                  <Input
                    id="quantity"
                    type="number"
                    min="0"
                    value={newProduct.quantity}
                    onChange={(e) => setNewProduct({ ...newProduct, quantity: Number.parseInt(e.target.value) || 0 })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="costPrice">Cost Price (PKR)</Label>
                  <Input
                    id="costPrice"
                    type="number"
                    min="0"
                    value={newProduct.costPrice}
                    onChange={(e) =>
                      setNewProduct({ ...newProduct, costPrice: Number.parseFloat(e.target.value) || 0 })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="sellingPrice">Selling Price (PKR)</Label>
                  <Input
                    id="sellingPrice"
                    type="number"
                    min="0"
                    value={newProduct.sellingPrice}
                    onChange={(e) =>
                      setNewProduct({ ...newProduct, sellingPrice: Number.parseFloat(e.target.value) || 0 })
                    }
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lowStockThreshold">Low Stock Alert</Label>
                  <Input
                    id="lowStockThreshold"
                    type="number"
                    min="0"
                    value={newProduct.lowStockThreshold}
                    onChange={(e) =>
                      setNewProduct({ ...newProduct, lowStockThreshold: Number.parseInt(e.target.value) || 0 })
                    }
                  />
                </div>
              </div>
              <div className="flex gap-2">
                <Button onClick={addProduct} className="bg-green-600 hover:bg-green-700">
                  <Plus className="w-4 h-4 mr-2" />
                  Add Product
                </Button>
                <Button variant="outline" onClick={clearAllProducts}>
                  <Trash2 className="w-4 h-4 mr-2" />
                  Clear All
                </Button>
                <Button variant="outline" onClick={exportToPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  Export PDF
                </Button>
                <Button variant="outline" onClick={exportToJPEG}>
                  <FileImage className="w-4 h-4 mr-2" />
                  Export JPEG
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Search and Filter */}
        {products.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.5 }}
            className="flex gap-4"
          >
            <div className="flex-1">
              <Input
                placeholder="Search products..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            <select
              className="px-3 py-2 border rounded-md bg-background"
              value={filterCategory}
              onChange={(e) => setFilterCategory(e.target.value)}
            >
              <option value="">All Categories</option>
              {categories.map((category) => (
                <option key={category} value={category}>
                  {category}
                </option>
              ))}
            </select>
          </motion.div>
        )}

        {/* Products Table */}
        {filteredProducts.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Inventory ({filteredProducts.length} products)</CardTitle>
              </CardHeader>
              <CardContent>
                <div id="inventory-table" className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b">
                        <th className="text-left p-2">Product</th>
                        <th className="text-left p-2">Category</th>
                        <th className="text-center p-2">Quantity</th>
                        <th className="text-right p-2">Cost Price</th>
                        <th className="text-right p-2">Selling Price</th>
                        <th className="text-right p-2">Profit Margin</th>
                        <th className="text-right p-2">Total Profit</th>
                        <th className="text-center p-2">Status</th>
                        <th className="text-center p-2">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filteredProducts.map((product) => {
                        const profitMargin = product.sellingPrice - product.costPrice
                        const profitPercentage =
                          product.costPrice > 0 ? ((profitMargin / product.costPrice) * 100).toFixed(1) : "0"
                        const totalProfit = profitMargin * product.quantity
                        const isLowStock = product.quantity <= product.lowStockThreshold

                        return (
                          <tr key={product.id} className="border-b hover:bg-muted/50">
                            <td className="p-2">
                              <div>
                                <p className="font-medium">{product.name}</p>
                                <p className="text-xs text-muted-foreground">
                                  Added {new Date(product.createdAt).toLocaleDateString()}
                                </p>
                              </div>
                            </td>
                            <td className="p-2">
                              <Badge variant="outline">{product.category}</Badge>
                            </td>
                            <td className="text-center p-2">
                              <Input
                                type="number"
                                min="0"
                                value={product.quantity}
                                onChange={(e) =>
                                  updateProduct(product.id, "quantity", Number.parseInt(e.target.value) || 0)
                                }
                                className="w-20 text-center"
                              />
                            </td>
                            <td className="text-right p-2">PKR {product.costPrice.toLocaleString()}</td>
                            <td className="text-right p-2">PKR {product.sellingPrice.toLocaleString()}</td>
                            <td className="text-right p-2">
                              <span className={profitMargin >= 0 ? "text-green-600" : "text-red-600"}>
                                {profitPercentage}%
                              </span>
                            </td>
                            <td className="text-right p-2">
                              <span className={totalProfit >= 0 ? "text-green-600" : "text-red-600"}>
                                PKR {totalProfit.toLocaleString()}
                              </span>
                            </td>
                            <td className="text-center p-2">
                              {isLowStock ? (
                                <Badge variant="destructive">Low Stock</Badge>
                              ) : (
                                <Badge variant="secondary">OK</Badge>
                              )}
                            </td>
                            <td className="text-center p-2">
                              <Button size="sm" variant="destructive" onClick={() => deleteProduct(product.id)}>
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {products.length === 0 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="text-center py-12"
          >
            <Package className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No Products in Inventory</h3>
            <p className="text-muted-foreground">
              Add your first product to start tracking inventory and managing stock levels.
            </p>
          </motion.div>
        )}
      </div>
    </PageWrapper>
  )
}
